### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by 1369841815** [ignacio-rocco/sparse-ncnet#10]
Hello, I like to run the demo to test the detection effect after setting up the environment, but the following error is prompted during the running process. I reinstalled it according to the official Minkowski Engine documentation, and I also put the installation screenshot below. I'm sorry to bother you again!!
![微信截图_20221124204429](https://user-images.githubusercontent.com/97372752/203787677-d51e5c20-9211-419f-af50-13d55e820c83.png)
![微信图片_20221124204438](https://user-images.githubusercontent.com/97372752/203787742-acd7cc3f-13dd-4ef6-9e60-56ef80e7c45f.png)

**Comment by 1369841815** [comment]
I checked. I think it's because of this

The Minkowski Engine version is updated. After I corrected one problem, another problem occurred. Would you please take a look? I want to go through the demo to see the effect. I'm sorry to bother you!!!
![qweqe](https://user-images.githubusercontent.com/97372752/203968697-66f3d779-87b4-4921-8258-05cbf8931a79.png)

**Comment by 1369841815** [comment]
I've found a way. Sorry！

**Comment by L-Yuke** [comment]
Hello, Can you share how you solved this problem？
