### ISSUE TITLE
eval problem

### ISSUE THREAD

**Issue by 1369841815** [ignacio-rocco/sparse-ncnet#11]
Hello, when I evaluated the HPatches dataset, I found that eval_hpatches_generate_plot.ipynb calls the files in the path datasets\hpatches\cache-top\. I want to know how these files are generated in the following path. The files saved in eval_hpatches_extract.py files are in the path below the dataset, which is different from your files. How do I evaluate them?
Sorry for wasting your precious time. I hope you can help me with this. Thank you！！！

**Comment by ignacio-rocco** [comment]
Hi, please check download_cache.sh here
https://github.com/mihaidusmanu/d2-net/tree/master/hpatches_sequences

Le lun. 28 nov. 2022 à 14:28, 1369841815 ***@***.***> a
écrit :

**Comment by 1369841815** [comment]
Hello, how do we generate our ncnet.densencnet_1600_hard_2k.npy file?
After I run python eval_hpatches_extract.py files, I generate 1_2.npz.sparsencnet_3200_hard_soft files under each file in the dataset instead of ncnet.densencnet_1600_hard_2k.npy files. If I want to generate this file, what should I do?
