### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by 1369841815** [ignacio-rocco/sparse-ncnet#8]
Hello, I'm sorry to bother you. I have a question about the dataset. Where should we download the ivd training dataset? I hope you can answer me when you have time. Thank you very much!!!

**Comment by ignacio-rocco** [comment]
Hi, this is available here:

https://github.com/ignacio-rocco/ncnet#getting-the-datasets

Best,
Ignacio

Le mer. 23 nov. 2022 à 09:59, 1369841815 ***@***.***> a
écrit :
